# docker container run -v $(pwd):/site -p 80:4000 bletvaska/jekyll

version: '3'
services:
  adminer:
    image: adminer
    volumes:
            - /www:/usr/share/adminer/html
    ports:
      - '8082:8080' 
    networks: 
      - wp-net
    depends_on:
      - mysql

  wordpress:
    image: wordpress
    env_file: database.env
    volumes:
            - /www:/usr/share/wordpress/html
    ports:
      - '8081:80'
    networks: 
      - wp-net
    depends_on:
      - mysql
     
  mysql:
    image: mysql
    container_name: 'Database'
    env_file: users.env
    volumes: 
      - 'wp-db:/var/lib/mysql'
    networks: 
      - wp-net
    command: '--default-authentication-plugin=mysql_native_password'

volumes:
  wp-db:

networks:
  wp-net:
